services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
        - "5672:5672"
        - "15672:15672"
    volumes:
        - .docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    ports: 
      - "5434:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
  maildev:
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"
  usernator:
    build: ./usernator
    ports: 
      - "3001:3000"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5434
      - DB_USERNAME=usernator
      - DB_PASSWORD=usernator
      - DB_DATABASE=usernator
      - SMTP_HOST=maildev
      - SMTP_PORT=1025
      - SMTP_USERNAME=app@codecanvas.de
      - SMTP_PASSWORD=cc
      - RABBITMQ_USERNAME=usernator
      - RABBITMQ_PASSWORD=usernator
      - RABBITMQ_HOST=rabbitmq:5672
      - TEMPLATE_BASE_URL=http://localhost:3000/web
    depends_on:
      - postgres
      - maildev
  authy:
    build: ./authy
    ports: 
      - "3002:3000"
    environment:
      - JWT_SECRET=secret
      - SERVICE_LOCATIONS={usernator="http://usernator:3000"}
    depends_on:
      - usernator
  executor:
    build: ./executor
    ports:
      - "3003:8000"
    environment:
      - RABBITMQ_USERNAME=executor
      - RABBITMQ_PASSWORD=executor
      - RABBITMQ_HOST=rabbitmq:5672
      - DATABASE_USERNAME=executor
      - DATABASE_PASSWORD=executor
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_NAME=executor
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - rabbitmq
      - postgres
volumes:
  db_data: