CREATE USER usernator WITH PASSWORD 'usernator';
CREATE DATABASE usernator;
GRANT ALL PRIVILEGES ON DATABASE usernator TO usernator;

CREATE USER tasky WITH PASSWORD 'tasky';
CREATE DATABASE tasky;
GRANT ALL PRIVILEGES ON DATABASE tasky TO tasky;

CREATE USER executor WITH PASSWORD 'executor';
CREATE DATABASE executor;
GRANT ALL PRIVILEGES ON DATABASE executor TO executor;


ALTER USER usernator WITH SUPERUSER;
ALTER USER tasky WITH SUPERUSER;
ALTER USER executor WITH SUPERUSER;
