services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    volumes:
      - .docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    ports:
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=<PG_ROOT_USERNAME>
      - POSTGRES_USER=<PG_ROOT_PASSWORD>
  mongodb:
    image: mongodb/mongodb-community-server:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=<MONGODB_ROOT_USERNAME>
      - MONGO_INITDB_ROOT_PASSWORD=<MONGODB_ROOT_PASSWORD>
  maildev:
    image: maildev/maildev
  usernator:
    image: ghcr.io/mathisburger/codecanvas-usernator:<RELEASE_VERSION>
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=<PG_USERNATOR_USERNAME>
      - DB_PASSWORD=<PG_USERNATOR_PASSWORD>
      - DB_DATABASE=<PG_USERNATOR_DATABASE>
      - SMTP_HOST=maildev
      - SMTP_PORT=1025
      - SMTP_USERNAME=app@codecanvas.de
      - SMTP_PASSWORD=cc
      - RABBITMQ_USERNAME=<RMQ_USERNATOR_USERNAME>
      - RABBITMQ_PASSWORD=<RMQ_USERNATOR_PASSWORD>
      - RABBITMQ_HOST=rabbitmq:5672
      - TASKY_ADDR=tasky:3001
      - TEMPLATE_BASE_URL=<PUBLIC_WEB_ADDR>
    depends_on:
      - postgres
      - maildev
  authy:
    image: ghcr.io/mathisburger/codecanvas-authy:<RELEASE_VERSION>
    ports:
      - "3002:3000"
    environment:
      - JWT_SECRET=<JWT_SECRET>
      - WHITELIST=["/usernator/reset_password","/usernator/submit_password","/usernator/register","/executor_ui/_next"]
      - SERVICE_LOCATIONS={usernator="http://usernator:3000", tasky="http://tasky:3000"}
    depends_on:
      - usernator
      - tasky
  tasky:
    image: ghcr.io/mathisburger/codecanvas-tasky:<RELEASE_VERSION>
    environment:
      - DB_NAME=<PG_TASKY_NAME>
      - DB_USERNAME=<PG_TASKY_USERNAME>
      - DB_PASSWORD=<PG_TASKY_PASSWORD>
      - DB_HOST=postgres:5432
      - USERNATOR_GRPC=http://usernator:3001
      - MONGO_HOST="mongodb:27017"
      - MONGO_USERNAME=<MONGO_TASKY_USERNAME>
      - MONGO_PASSWORD=<MONGO_TASKY_PASSWORD>
      - MONGO_DATABASE=executor_files
      - EXECUTOR_HTTP=http://executor:8000
    depends_on:
      - usernator
      - postgres
  executor:
    image: ghcr.io/mathisburger/codecanvas-tasky:<RELEASE_VERSION>
    environment:
      - RABBITMQ_USERNAME=<RMQ_EXECUTOR_USERNAME>
      - RABBITMQ_PASSWORD=<RMQ_EXECUTOR_PASSWORD>
      - RABBITMQ_HOST=rabbitmq:5672
      - DATABASE_USERNAME=<PG_EXECUTOR_USERNAME>
      - DATABASE_PASSWORD=<PG_EXECUTOR_PASSWORD>
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_NAME=<PG_EXECUTOR_DATABASE>
      - MONGODB_USERNAME=<MONGODB_EXECUTOR_USERNAME>
      - MONGODB_PASSWORD=<MONGODB_EXECUTOR_PASSWORD>
      - MONGODB_HOST=mongodb:27017
      - MONGODB_DATABASE=executor_files
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - rabbitmq
      - postgres
  executor_ui:
    image: runabol/tork-web
    ports:
      - "3007:8100"
    environment:
      - BACKEND_URL=http://executor:8000
    depends_on:
      - executor
volumes:
  db_data: