[package]
name = "tasky"
version = "0.1.0"
edition = "2021"

[dependencies]
diesel_migrations = "2.2.0"
diesel = { version = "2.2.0", features = ["postgres"] }
serde = {version = "1", features = ["derive"]}
serde_json = "1.0"
log = {version = "0.4.22", features = ["serde", "std"]}
figment = { version = "0.10.18", features = ["toml", "env"] }
toml = "0.8.19"
pretty_env_logger = "0.5.0"