db_name = "tasky"
db_username = "tasky"
db_host = "localhost:5434"
db_password = "tasky"
usernator_grpc = "http://127.0.0.1:3004"
mongo_host = "localhost:27017"
mongo_username = "tasky"
mongo_password = "tasky"
mongo_database = "executor_files"
