on:
  release:
    types: [published]

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Create proto symlinks
        run: ln ./usernator/api.proto ./tasky/api.proto
      - name: set up buildx
        uses: docker/setup-buildx-action@v1
      - name: log in to ghcr
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: mathisburger
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build authy
        uses: docker/build-push-action@v2
        with:
          context: ./authy
          push: true
          tags: ghcr.io/mathisburger/codecanvas-authy:latest
      - name: Build executor
        uses: docker/build-push-action@v2
        with:
          context: ./executor
          push: true
          tags: ghcr.io/mathisburger/codecanvas-executor:latest
      - name: Build tasky
        uses: docker/build-push-action@v2
        with:
          context: ./tasky
          push: true
          tags: ghcr.io/mathisburger/codecanvas-tasky:latest
      - name: Build usernator
        uses: docker/build-push-action@v2
        with:
          context: ./usernator
          push: true
          tags: ghcr.io/mathisburger/codecanvas-usernator:latest
      