name: Test

on: [push]

jobs:
  build-web-container:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: set up buildx
        uses: docker/setup-buildx-action@v1
      - name: Build web
        uses: docker/build-push-action@v2
        with:
          context: ./web
          push: false
          tags: web